{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception('oops')\nE       Exception: oops\n\nTK_GUI\\gui_12.py:28: Exception"}, "start": 1607337674634, "stop": 1607337674635, "uuid": "5c0c29f5-70b4-43c3-9f9b-2b8baf2fea99", "historyId": "1375d96889065df121da8b9b6e3bd2b5", "testCaseId": "36e18432ebbb4ef671abc86c0089116e", "fullName": "TK_GUI.gui_12#test_broken", "labels": [{"name": "parentSuite", "value": "TK_GUI"}, {"name": "suite", "value": "gui_12"}, {"name": "host", "value": "duang"}, {"name": "thread", "value": "12904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TK_GUI.gui_12"}]}