{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "def test_failure():\n        \"\"\"this test is  fails\"\"\"\n>       assert False\nE       AssertionError\n\nTK_GUI\\gui_12.py:19: AssertionError"}, "description": "this test is  fails", "start": 1607337674513, "stop": 1607337674514, "uuid": "e8ac34d9-61b3-490a-9d20-b7c70d6d49d8", "historyId": "19df8d2b8c84a357a66ff6efdaf1e25c", "testCaseId": "e4d6fdb820d9de19c7bf9383e7a976d6", "fullName": "TK_GUI.gui_12#test_failure", "labels": [{"name": "parentSuite", "value": "TK_GUI"}, {"name": "suite", "value": "gui_12"}, {"name": "host", "value": "duang"}, {"name": "thread", "value": "12904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TK_GUI.gui_12"}]}