{"name": "test_simple_assume[0-1]", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntoor\\pytest01.py:42: AssumptionFailure\n>>\tpytest.assume(x == y)\nAssertionError: assert False\n\ntoor\\pytest01.py:44: AssumptionFailure\n>>\tpytest.assume(False)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               toor\\pytest01.py:42: AssumptionFailure\nE               >>\tpytest.assume(x == y)\nE               AssertionError: assert False\nE               \nE               toor\\pytest01.py:44: AssumptionFailure\nE               >>\tpytest.assume(False)\nE               AssertionError: assert False\n\nc:\\users\\duang01\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\six.py:692: FailedAssumption"}, "parameters": [{"name": "x", "value": "0"}, {"name": "y", "value": "1"}], "start": 1598263090181, "stop": 1598263090214, "uuid": "d969a78d-1bdd-468b-b9fa-b0d23f1d52cf", "historyId": "49a120c59c0c45f33ff19d7086e7a08e", "testCaseId": "79bd3a3afcd51776622374198af6a7d0", "fullName": "toor.pytest01#test_simple_assume", "labels": [{"name": "parentSuite", "value": "toor"}, {"name": "suite", "value": "pytest01"}, {"name": "host", "value": "duang"}, {"name": "thread", "value": "7008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "toor.pytest01"}]}